server:
  port: 8081
  servlet:
    encoding:
      charset: utf-8
      force: true
      enabled: true

# DataSource Config
spring:
  datasource:
    url: jdbc:mysql://121.43.40.44:3306/flash_sale?serverTimezone=Asia/Shanghai
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  redis:
    host: 121.43.40.44
    port: 6379
    database: 1

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


token-config:
  secret: f4e2e52034348f86b67cde581c0f9eb5
  header: token
  expire: 604800 # token有效时长，7天，单位秒
  tokenHeader: Authorization

rocketmq:
  name-server: 121.43.40.44:9876
  producer:
    group: flash_sale_producer
  consumer:
    group: flash_sale_consumer
  send-message-timeout: 3000

