---
--- Generated by Luanalysis
--- Created by Administrator.
--- DateTime: 2023/4/16 0016 14:24
---
---
--- KEYS[1] : stockID
--- ARGV[1] : all
--- ARGV[2] : sale
local all = redis.call('hget',KEYS[1], ARGV[1]);
local sale = redis.call('hget',KEYS[1], ARGV[2]);
local sale  = sale + 1;
if(tonumber(all) >= tonumber(sale)) then
    redis.call('hincrby', KEYS[1], ARGV[2], 1);
    return true;
end;
    return false;