---
--- Generated by Luanalysis
--- Created by Administrator.
--- DateTime: 2023/4/16 0016 16:31
---
local sale = redis.call('hget',KEYS[1], ARGV[1]);
local sale  = sale - 1;
redis.call('hset', KEYS[1], ARGV[1], sale);
return true;
